name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain
      uses: ./.github/actions/setup-builder
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
